config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :users

  resources :recognitions do
    resources :users, only: :create
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recognition.rb
class Recognition < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :value, presence: true
  validates :message, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recognitions

  validates :name, presence: true
  validates :title, presence: true
  validates :manager, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recognitions_controller.rb
class RecognitionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  # new recognition
  def new
    @recognition = Recognition.new
  end
  
  # create new recognition
  def create
    @recognition = Recognition.new(recognition_params)
    if @recognition.save
      redirect_to users_path, notice: "Recognition is sent to your coworker & his/ her manager."
    else 
      render :new
    end
  end
  
  private

  # parameter for creating new recognition
  def recognition_params
    params.require(:recognition).permit(:name, :value, :message)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # show all users except current user
  def index
    @users = User.where.not(id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recognitions_helper.rb
module RecognitionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanyXPortal</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </div>
  </body>
</html>

app/views/recognitions/new.html.erb
<%= render "shared/navbar" %>
<div class="container mt-5">
  <%# recognition form %>
  <%= simple_form_for @recognition, remote:true do |f| %>
  <%= f.input :name, class: "form-control" %><br/>
  <%= f.input :value, class: "form-control mb-1" %><br/>
  <%= f.input :message, class: "form-control" %><br/>
  <div class="d-flex justify-content-between mt-3">
    <%= link_to "Back", users_path, class: "btn btn-secondary" %>
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://res.cloudinary.com/kenn/image/upload/v1628190592/x_logo.png" alt="logo" width="30" height="24" class="d-inline-block align-text-top">
    </a>
    <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, class: "text-white text-decoration-none" %>
  </div>
</nav>

app/views/users/index.html.erb
<%= render "shared/navbar" %>
<%# notice appears if the user sends a recognotion form %>
    <% if notice %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
<div class="container mt-5">
  <div class="card text-center p-5">
  <%# recognition %>
    <h1>Would you like to recognize your coworker?</h1>
    <div>
      <%= link_to "Sure", new_recognition_path, class: "btn btn-primary btn-lg mt-4" %> 
    </div>
  </div>
  <%# list of coworkers %>
  <h1 class="mt-5">Coworkers</h1>
  <div class="card-container mb-5">
    <% @users.each do |user| %>
      <div class="card p-3">
        <h5><%= user.name %></h5>
        <p><%= user.title %></p>
        <p>Manager: <%= user.manager %></p>
      </div>
    <% end %>
  </div>
</div>